<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            color: #333;
            line-height: 1.4;
            margin: 0;
            padding: 0;
        }

        /* Header */
        .header {
            background-color: #2c5aa0;
            color: white;
            padding: 20px;
            text-align: center;
            border-bottom: 2px solid #1e3a5f;
        }

        .header h1 {
            font-size: 24px;
            margin: 0;
            font-weight: 600;
        }

        .header p {
            font-size: 12px;
            margin: 5px 0 0;
            opacity: 0.9;
        }

        /* Summary Stats */
        .summary {
            display: flex;
            justify-content: space-around;
            padding: 20px;
            background-color: #f9f9f9;
            margin: 10px 0;
        }

        .stat-card {
            text-align: center;
        }

        .stat-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .stat-value {
            font-size: 18px;
            font-weight: 600;
            color: #2c5aa0;
        }

        /* Filter Info */
        .filter-info {
            padding: 10px 20px;
            font-size: 12px;
            color: #666;
            background-color: #f1f1f1;
            margin-bottom: 10px;
        }

        .filter-info strong {
            color: #333;
        }

        /* Table */
        .table-container {
            padding: 0 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #2c5aa0;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 12px;
            font-weight: 600;
        }

        td {
            padding: 8px;
            font-size: 12px;
            border-bottom: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Status Badge */
        .status-badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: 600;
            text-transform: uppercase;
        }

        .status-accepted { background-color: #d4edda; color: #155724; }
        .status-pending { background-color: #fff3cd; color: #856404; }
        .status-rejected { background-color: #f8d7da; color: #721c24; }
        .status-taken { background-color: #cce5ff; color: #004085; }

        /* Empty State */
        .empty-state {
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 12px;
        }

        /* Footer */
        .footer {
            padding: 10px 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
            text-align: center;
            margin-top: 20px;
        }

        @media print {
            body { margin: 0; }
            .page-break { page-break-after: always; }
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Donations Report</h1>
        <p>Generated by Waste2Product - {{ $date }}</p>
    </div>

    <!-- Summary Statistics -->
    <div class="summary">
        <div class="stat-card">
            <div class="stat-label">Total Donations</div>
            <div class="stat-value">{{ $donations->count() }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Total Quantity</div>
            <div class="stat-value">{{ $donations->sum('quantity') }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Unique Donors</div>
            <div class="stat-value">{{ $donations->pluck('user_id')->unique()->count() }}</div>
        </div>
    </div>

    <!-- Filter Information -->
    @if($search || ($type && $type !== 'all'))
        <div class="filter-info">
            <strong>Filters Applied:</strong>
            @if($search) Search: <strong>{{ $search }}</strong>@endif
            @if($type && $type !== 'all') | Type: <strong>{{ ucfirst($type) }}</strong>@endif
        </div>
    @endif

    <!-- Donations Table -->
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Donor Name</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Type</th>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($donations as $donation)
                    <tr>
                        <td>{{ $donation->user->name ?? 'Anonymous' }}</td>
                        <td>{{ $donation->product_name }}</td>
                        <td>{{ $donation->quantity }}</td>
                        <td>{{ ucfirst($donation->type) }}</td>
                        <td>{{ $donation->location }}</td>
                        <td>{{ \Carbon\Carbon::parse($donation->donation_date)->format('Y-m-d') }}</td>
                        <td>
                            <span class="status-badge status-{{ strtolower($donation->status) }}">
                                {{ ucfirst($donation->status) }}
                            </span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">
                            <div class="empty-state">No donations found matching your criteria.</div>
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <!-- Footer -->
    <div class="footer">
        <p>Waste2Product © {{ date('Y') }} | Generated: {{ $date }}</p>
    </div>
</body>
</html>