version: '3.8'

services:
  laravel_app:
    image: webdevops/php-nginx:8.2
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./:/app:cached
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:MPJ+58oBeh5/XYsj8Toy879h6311dIS1P15vwhqh6Ss=
      DB_CONNECTION: mysql
      DB_HOST: mysql-laravel
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      WEB_DOCUMENT_ROOT: /app/public   # <-- Ajouté ici
    depends_on:
      - mysql-laravel

  mysql-laravel:
    image: mysql:8.0
    container_name: mysql-laravel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
